version: '2'
services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8080:80"
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=very-secret-password
      - MYSQL_DATABASE=testappdb
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=not-so-secret-password
    volumes:
      - ./database:/var/lib/mysql
